name: Test with Emacs
on: [push]
jobs:
  test-with-emacs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        emacs_version: [26.1, 26.3, 27.2, 28.2, 29.4, 30.2]

    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Pyrefly
        run: |
          python -m venv .venv
          .venv/bin/pip install pyrefly
      - name: Test with Emacs
        run: |
          export PYREFLY_BIN_DIR=$(pwd)/.venv/bin
          make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Compile
        run: |
          make compile
